name: Deploy AWS Lambda

on:
  push:
    branches:
      - main


permissions:
    id-token: write # This is required for requesting the JWT
    contents: read  # This is required for actions/checkout
    
jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      run: |
        echo ${{ secrets.AWS_ACCESS_KEY_ID }} > aws_access_key_id
        echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} > aws_secret_access_key
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region us-east-1
   
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest

    - name: Terraform Init
      run: |
        cd infra
        terraform init 
        terraform validate

    - name: Terraform Destroy
      run: |
        cd infra
        terraform destroy -auto-approve

    - name: Terraform Plan
      run: |
        cd infra
        terraform plan -input=false -out=tfplan

    - name: Terraform Apply
      run: |
        cd infra
        terraform apply -input=false  -auto-approve

    - name: Save Terraform state
      uses: terraform-linters/action/terraform-state@v0.1.0
      with:
        path: ./infra/terraform.tfstate